### ISSUE TITLE
Movies don't fecth data from torrent in MacOs

### ISSUE THREAD

**Issue by ruipisco** [lubo/KODI-Popcorn-Time#2]
After installing the add-on in MacOs the movie list already works but when select the movies the data don't load the peers and the seeds and the fetch pop-up closes immediately, and the movei will not play.

**Comment by ruipisco** [comment]
here is the logs to help with the torrent2http error:

<details>
  <summary>Click to expand</summary>
  
```
2021-11-30 13:14:00.155 T:137032    INFO <general>: [plugin.video.kodipopcorntime] (base3-context) 1080p
2021-11-30 13:14:00.155 T:137032    INFO <general>: [plugin.video.kodipopcorntime] (base3-context) 720p
2021-11-30 13:14:00.156 T:137032    INFO <general>: [plugin.video.kodipopcorntime] (base3-context) 480p
2021-11-30 13:14:00.157 T:137032   ERROR <general>: NEWADDON Unknown Video Info Key "context_menu"
2021-11-30 13:14:00.158 T:137032   ERROR <general>: NEWADDON Unknown Video Info Key "replace_context_menu"
2021-11-30 13:14:00.159 T:137032    INFO <general>: [plugin.video.kodipopcorntime] (settings-date) no condition met 2021-11-30
2021-11-30 13:14:00.161 T:137032    INFO <general>: [plugin.video.kodipopcorntime] (Browse) Finish
2021-11-30 13:14:00.164 T:137032    INFO <general>: CPythonInvoker(5, /Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/addon.py): script successfully run
2021-11-30 13:14:00.260 T:137032    INFO <general>: Python interpreter stopped
2021-11-30 13:14:02.355 T:137077    INFO <general>: initializing python engine.
2021-11-30 13:14:02.851 T:137077 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-11-30 13:14:02.922 T:137077    INFO <general>: Skipped 1 duplicate messages..
2021-11-30 13:14:02.922 T:137077    INFO <general>: [plugin.video.kodipopcorntime] (Main) Starting KODI Popcorn Time version 1.7.6 build 2 - Platform: darwin x64
2021-11-30 13:14:02.925 T:137077 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-11-30 13:14:02.927 T:137077    INFO <general>: Skipped 1 duplicate messages..
2021-11-30 13:14:02.927 T:137077    INFO <general>: [plugin.video.kodipopcorntime] (Torrent) Initialize torrent engine
2021-11-30 13:14:02.927 T:137077    INFO <general>: [plugin.video.kodipopcorntime] (Torrent Player) Loading
2021-11-30 13:14:03.709 T:136326    INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2021-11-30 13:14:03.723 T:137100    INFO <general>: [plugin.video.kodipopcorntime] (Thread-1) (Torrent) Find free port
2021-11-30 13:14:03.723 T:137100    INFO <general>: [plugin.video.kodipopcorntime] (Thread-1) (Torrent) Starting torrent2http
2021-11-30 13:14:03.807 T:137100    INFO <general>: [plugin.video.kodipopcorntime] (Thread-1) (Torrent) ConnectionRefusedError: [Errno 61] Connection refused
2021-11-30 13:14:04.694 T:137077   FATAL <general>: Skipped 648 duplicate messages..
2021-11-30 13:14:04.694 T:137077   FATAL <general>: [plugin.video.kodipopcorntime] Traceback (most recent call last):
                                                     File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/addon.py", line 38, in <module>
                                                       getattr(gui, params.pop('endpoint', 'index'))(params.pop('mediaType', '')).show(**params)
                                                     File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/player.py", line 106, in show
                                                       TorrentPlayer().playTorrentFile(self.mediaSettings, build_magnetFromMeta(params[quality], "quality %s" %quality), item, subtitle)
                                                     File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 434, in playTorrentFile
                                                       raise Abort()
                                                     File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 42, in __exit__
                                                       self.close()
                                                     File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 379, in close
                                                       super(Loader, self).close()
                                                     File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 51, in close
                                                       self.raiseAnyError()
                                                     File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 33, in raiseAnyError
                                                       raise self._exc_info[1].with_traceback(self._exc_info[2])
                                                     File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 23, in ___run
                                                       self.__target()
                                                     File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 257, in _run
                                                       if self._TEngine.start() and self._getPlayFile() and self._checkData() and self._preloading(self._item.get('stream_info', {}).get('video', {}).get('duration', 0)):
                                                     File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 124, in start
                                                       raise TorrentError("Can't start torrent2http")
                                                   kodipopcorntime.exceptions.TorrentError: Can't start torrent2http
                                                   
2021-11-30 13:14:04.695 T:137077    INFO <general>: CPythonInvoker(6, /Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/addon.py): script successfully run
2021-11-30 13:14:04.729 T:137077   ERROR <general>: Exception ignored in: 
2021-11-30 13:14:04.730 T:137077   ERROR <general>: <function Thread.__del__ at 0x6000001e46d0>
2021-11-30 13:14:04.730 T:137077   ERROR <general>: 
                                                   
2021-11-30 13:14:04.731 T:137077   ERROR <general>: Traceback (most recent call last):
                                                   
2021-11-30 13:14:04.731 T:137077   ERROR <general>:   File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 46, in __del__
                                                   
2021-11-30 13:14:04.736 T:137077   ERROR <general>:     
2021-11-30 13:14:04.736 T:137077   ERROR <general>: self.close()
2021-11-30 13:14:04.737 T:137077   ERROR <general>: 
                                                   
2021-11-30 13:14:04.737 T:137077   ERROR <general>:   File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 379, in close
                                                   
2021-11-30 13:14:04.745 T:137077   ERROR <general>:     
2021-11-30 13:14:04.746 T:137077   ERROR <general>: super(Loader, self).close()
2021-11-30 13:14:04.746 T:137077   ERROR <general>: 
                                                   
2021-11-30 13:14:04.746 T:137077   ERROR <general>:   File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 51, in close
                                                   
2021-11-30 13:14:04.756 T:137077   ERROR <general>:     
2021-11-30 13:14:04.757 T:137077   ERROR <general>: self.raiseAnyError()
2021-11-30 13:14:04.757 T:137077   ERROR <general>: 
                                                   
2021-11-30 13:14:04.757 T:137077   ERROR <general>:   File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 33, in raiseAnyError
                                                   
2021-11-30 13:14:04.770 T:137077   ERROR <general>:     
2021-11-30 13:14:04.771 T:137077   ERROR <general>: raise self._exc_info[1].with_traceback(self._exc_info[2])
2021-11-30 13:14:04.771 T:137077   ERROR <general>: 
                                                   
2021-11-30 13:14:04.771 T:137077   ERROR <general>:   File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/threads.py", line 23, in ___run
                                                   
2021-11-30 13:14:04.788 T:137077   ERROR <general>:     
2021-11-30 13:14:04.788 T:137077   ERROR <general>: self.__target()
2021-11-30 13:14:04.789 T:137077   ERROR <general>: 
                                                   
2021-11-30 13:14:04.789 T:137077   ERROR <general>:   File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 257, in _run
                                                   
2021-11-30 13:14:04.801 T:137077   ERROR <general>:     
2021-11-30 13:14:04.802 T:137077   ERROR <general>: if self._TEngine.start() and self._getPlayFile() and self._checkData() and self._preloading(self._item.get('stream_info', {}).get('video', {}).get('duration', 0)):
2021-11-30 13:14:04.802 T:137077   ERROR <general>: 
                                                   
2021-11-30 13:14:04.802 T:137077   ERROR <general>:   File "/Users/ruipisco/Library/Application Support/Kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/torrent.py", line 124, in start
                                                   
2021-11-30 13:14:04.808 T:137077   ERROR <general>:     
2021-11-30 13:14:04.809 T:137077   ERROR <general>: raise TorrentError("Can't start torrent2http")
2021-11-30 13:14:04.809 T:137077   ERROR <general>: 
                                                   
2021-11-30 13:14:04.810 T:137077   ERROR <general>: kodipopcorntime.exceptions
2021-11-30 13:14:04.810 T:137077   ERROR <general>: .
2021-11-30 13:14:04.811 T:137077   ERROR <general>: TorrentError
2021-11-30 13:14:04.811 T:137077   ERROR <general>: : 
2021-11-30 13:14:04.811 T:137077   ERROR <general>: Can't start torrent2http
2021-11-30 13:14:04.811 T:137077   ERROR <general>: 
```
</details>

**Comment by lubo** [comment]
Hi. I don't use macOS, therefore I won't be looking into this. As always, feel free to send a pull request.

P.S.: Please, be so kind and use the proper formatting when posting structured text. Also, use collapsible sections when posting long snippets.

**Comment by lubo** [comment]
Actually, this looks like markop159/KODI-Popcorn-Time#108 and since it isn't specific to this fork, I'm closing this as a duplicate.
