### ISSUE TITLE
KODI Popcorn Time error

### ISSUE THREAD

**Issue by TomislavBombas** [lubo/KODI-Popcorn-Time#9]
PLugin doesn't start, reports error. Fedora 40. Error in python script.
Log entry low:
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'AttributeError'>
Error Contents: module 'xbmc' has no attribute 'translatePath'
Traceback (most recent call last):
 File "/home/$USER/.kodi/addons/plugin.video.kodipopcorntime/addon.py", line 7, in <module>
   from kodipopcorntime import gui
 File "/home/$USER/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/__init__.py", line 1, in <module>
   from .browse import Browse as browse
 File "/home/$USER/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/browse.py", line 3, in <module>
   from .base3 import _Base3
 File "/home/$USER/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/gui/base3.py", line 7, in <module>
   from kodipopcorntime import favourites
 File "/home/$USER/.kodi/addons/plugin.video.kodipopcorntime/resources/lib/kodipopcorntime/favourites.py", line 13, in <module>
   __addondir__ = xbmc.translatePath(__addon__.getAddonInfo('profile'))
                  ^^^^^^^^^^^^^^^^^^
AttributeError: module 'xbmc' has no attribute 'translatePath'
-->End of Python script error report<--

**Comment by lubo** [comment]
Already resolved in 02366db6be0e70c9b5efd19b079ffd464a8fa29b.
